-- SAMURAI CODE DOJO - Filosofia e Atalhos do Guerreiro do Código
-- O caminho do verdadeiro Samurai é através do Vim

local M = {}

M.philosophy = {
  "🗡️  BUSHIDŌ DO CÓDIGO (Caminho do Samurai Codificador)",
  "",
  "「Gi (義)」 RETIDÃO",
  "  Escreve código limpo e honrado",
  "  <leader>cf  → Formata seu código (tempera a lâmina)",
  "  <leader>ca  → Code actions (técnicas apuradas)",
  "",
  "「Yu (勇)」 CORAGEM",
  "  Refatora sem medo",
  "  <leader>rn  → Renomeia símbolos (mudança decisiva)",
  "  <leader>ca  → Aplica ações automáticas",
  "",
  "「Meiyo (名誉)」 HONRA",
  "  Mantém o histórico git limpo",
  "  <leader>gg  → Painel git (rastreia seu legado)",
  "  <leader>hs  → Stage hunk (cuida de cada mudança)",
  "",
  "「Chugi (忠義)」 LEALDADE",
  "  Conhece teus LSPs",
  "  :LspInfo    → Verifica teus aliados",
  "  <leader>lm  → Mason (tempera tuas ferramentas)",
  "",
  "「Meiyo (名誉)」 FRUGALIDADE",
  "  Menos plugins, mais poder",
  "  <leader>?   → Cheatsheet (conhece tuas 100 técnicas)",
  "",
  "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  "",
  "🥋 TÉCNICAS ESSENCIAIS DO SAMURAI",
  "",
  "⚔️  NAVEGAÇÃO (As 4 Direções)",
  "  gd  → Ir para definição (ataque frontal)",
  "  gr  → Ver referências (rodeia o inimigo)",
  "  gi  → Ir para implementação (encontra a essência)",
  "  gt  → Type definition (conhece a forma)",
  "",
  "🗡️  EDIÇÃO (Golpes de Espada)",
  "  <leader>rn → Renomear (corta e muda)",
  "  <leader>ca → Code actions (técnica especial)",
  "  <leader>/  → Comenta (marca território)",
  "  <M-Up/Dn>  → Move linha (fluxo como água)",
  "",
  "🎯 HOVERING (O Olho do Samurai)",
  "  K          → Documentação (ver a verdade)",
  "  <leader>hh → Hover robusto (segunda lâmina)",
  "  <leader>hs → Signature help (conhece os parâmetros)",
  "  :HoverHelp → Guia de hover",
  "",
  "🔍 BUSCA (Rastreador de Presas)",
  "  Cmd+P      → Buscar arquivo (arco tenso)",
  "  Cmd+F      → Buscar no arquivo (foco cerrado)",
  "  Cmd+Shift+F → Live grep (rede larga)",
  "  <leader>ff → Find files (equipe completa)",
  "",
  "📋 GIT (O Registro da Honra)",
  "  <leader>gg → Painel git (mural de batalhas)",
  "  ]c / [c    → Próximo/anterior hunk",
  "  <leader>hs → Stage hunk (marca sua vitória)",
  "  <leader>hb → Blame (vê quem foi responsável)",
  "",
  "🧪 TESTES (Prova de Ferro)",
  "  <leader>tt → Rodar testes (prova da lâmina)",
  "  <leader>tn → Próximo teste",
  "  <leader>ts → Summary (resultado da batalha)",
  "",
  "🐛 DEBUG (Busca do Inimigo Invisível)",
  "  <leader>db → Breakpoint (armadilha)",
  "  <leader>dc → Continue (avança o ataque)",
  "  <leader>do → Step over (golpe preciso)",
  "  <leader>di → Step into (penetra fundo)",
  "",
  "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  "",
  "💡 HABILIDADES ESPECIAIS",
  "",
  "✨ SELEÇÃO (Habilidade Suprema)",
  "  Cmd+A      → Seleciona tudo (abraça o vazio)",
  "  Cmd+Shift+L → Seleção multilinha",
  "",
  "🎨 VISUAL (Estética da Espada)",
  "  <leader>uw → Twilight (foco no essencial)",
  "  <leader>ui → Inlay hints (pistas invisíveis)",
  "  <leader>so → Symbol outline (estrutura do castelo)",
  "",
  "📍 MARCAS (Caminhos Memoráveis)",
  "  <leader>ha → Add harpoon (marca este lugar)",
  "  <leader>hm → Menu harpoon (volta para casa)",
  "  <leader>h1-4 → Ir para marca 1-4 (teletransporte)",
  "",
  "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  "",
  "🎯 OS 5 ANÉIS (Gorin no Sho) DO CÓDIGO",
  "",
  "1️⃣  Terra (Fundação)",
  "    Conhece teu Neovim: :help, :checkhealth",
  "",
  "2️⃣  Água (Fluidez)",
  "    Navega como água: hjkl, Ctrl+hjkl, splits",
  "",
  "3️⃣  Fogo (Velocidade)",
  "    Ataca rápido: Cmd+P, Cmd+/, busca",
  "",
  "4️⃣  Vento (Adaptabilidade)",
  "    Adapta-te: LSPs, snippets, customização",
  "",
  "5️⃣  Vazio (Domínio)",
  "    Transcende: Vim motions, plugin chains, magia",
  "",
  "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  "",
  "🙏 MANTRA DO SAMURAI CODER",
  "",
  "  'Vi no koto wo seyo' (為せんことをなせ)",
  "  'Faz o que você deve fazer'",
  "",
  "  Domina Vim → Transforma em Neovim → Torna-se parte da máquina",
  "",
  "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  "",
  "⌛ DICA DO DIA",
  "  Pratique um atalho por dia",
  "  Em 100 dias, serás imparável",
  "  Zanshin (残心) - Mantenha a mente alerta sempre",
  "",
}

M.setup = function()
  vim.api.nvim_create_user_command("DojoPhilosophy", function()
    local lines = M.philosophy
    local buf = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
    vim.api.nvim_buf_set_option(buf, "filetype", "help")
    vim.api.nvim_buf_set_option(buf, "modifiable", false)
    
    vim.cmd("new | b" .. buf)
    vim.keymap.set("n", "q", "<Cmd>bd<CR>", { buffer = buf })
  end, {})

  -- Atalho rápido
  vim.keymap.set("n", "<leader>d", ":DojoPhilosophy<CR>", { desc = "🥋 Dojo (Filosofia Samurai)" })
end

return M
